export const fakeTweets = [
  {
    created_at: 'Sat Nov 28 17:52:18 +0000 2020',
    id: 1332744140187181000,
    id_str: '1332744140187181062',
    text: 'This contains a gif https://t.co/Zd3HzAhqwB',
    display_text_range: [0, 19],
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 18,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [
        {
          id: 1332744130984878000,
          id_str: '1332744130984878082',
          indices: [20, 43],
          description: 'Sad Lilo And Stitch GIF',
          media_url: 'http://pbs.twimg.com/tweet_video_thumb/En7budfXIAIPlsv.jpg',
          media_url_https: 'https://pbs.twimg.com/tweet_video_thumb/En7budfXIAIPlsv.jpg',
          url: 'https://t.co/Zd3HzAhqwB',
          display_url: 'pic.twitter.com/Zd3HzAhqwB',
          expanded_url:
            'https://twitter.com/pollomarzo/status/1332744140187181062/photo/1',
          type: 'photo',
          sizes: {
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 500, h: 184, resize: 'fit' },
            medium: { w: 500, h: 184, resize: 'fit' },
            large: { w: 500, h: 184, resize: 'fit' },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1332744130984878000,
          id_str: '1332744130984878082',
          indices: [20, 43],
          description: 'Sad Lilo And Stitch GIF',
          media_url: 'http://pbs.twimg.com/tweet_video_thumb/En7budfXIAIPlsv.jpg',
          media_url_https: 'https://pbs.twimg.com/tweet_video_thumb/En7budfXIAIPlsv.jpg',
          url: 'https://t.co/Zd3HzAhqwB',
          display_url: 'pic.twitter.com/Zd3HzAhqwB',
          expanded_url:
            'https://twitter.com/pollomarzo/status/1332744140187181062/photo/1',
          type: 'animated_gif',
          video_info: {
            aspect_ratio: [125, 46],
            variants: [
              {
                bitrate: 0,
                content_type: 'video/mp4',
                url: 'https://video.twimg.com/tweet_video/En7budfXIAIPlsv.mp4',
              },
            ],
          },
          sizes: {
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 500, h: 184, resize: 'fit' },
            medium: { w: 500, h: 184, resize: 'fit' },
            large: { w: 500, h: 184, resize: 'fit' },
          },
        },
      ],
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606585938866',
  },
  {
    created_at: 'Sat Nov 28 17:52:41 +0000 2020',
    id: 1332744235049693200,
    id_str: '1332744235049693188',
    text: 'This contains a pic https://t.co/BAV4zg8MR0',
    display_text_range: [0, 19],
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 19,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [
        {
          id: 1332744232164003800,
          id_str: '1332744232164003840',
          indices: [20, 43],
          media_url: 'http://pbs.twimg.com/media/En7b0WaWEAA-xXX.jpg',
          media_url_https: 'https://pbs.twimg.com/media/En7b0WaWEAA-xXX.jpg',
          url: 'https://t.co/BAV4zg8MR0',
          display_url: 'pic.twitter.com/BAV4zg8MR0',
          expanded_url:
            'https://twitter.com/pollomarzo/status/1332744235049693188/photo/1',
          type: 'photo',
          sizes: {
            large: { w: 1152, h: 2048, resize: 'fit' },
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 383, h: 680, resize: 'fit' },
            medium: { w: 675, h: 1200, resize: 'fit' },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1332744232164003800,
          id_str: '1332744232164003840',
          indices: [20, 43],
          media_url: 'http://pbs.twimg.com/media/En7b0WaWEAA-xXX.jpg',
          media_url_https: 'https://pbs.twimg.com/media/En7b0WaWEAA-xXX.jpg',
          url: 'https://t.co/BAV4zg8MR0',
          display_url: 'pic.twitter.com/BAV4zg8MR0',
          expanded_url:
            'https://twitter.com/pollomarzo/status/1332744235049693188/photo/1',
          type: 'photo',
          sizes: {
            large: { w: 1152, h: 2048, resize: 'fit' },
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 383, h: 680, resize: 'fit' },
            medium: { w: 675, h: 1200, resize: 'fit' },
          },
        },
      ],
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606585961483',
  },
  {
    created_at: 'Sat Nov 28 17:52:55 +0000 2020',
    id: 1332744292545261600,
    id_str: '1332744292545261575',
    text: 'This contains a poll',
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 20,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606585975191',
  },
  {
    created_at: 'Sat Nov 28 17:53:54 +0000 2020',
    id: 1332744541166768000,
    id_str: '1332744541166768134',
    text: 'This contains a video https://t.co/VReJvEzRDT',
    display_text_range: [0, 21],
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 21,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [
        {
          id: 1332744448724308000,
          id_str: '1332744448724307969',
          indices: [22, 45],
          additional_media_info: { monetizable: false },
          media_url:
            'http://pbs.twimg.com/ext_tw_video_thumb/1332744448724307969/pu/img/fZGy15pnJJIpnqXL.jpg',
          media_url_https:
            'https://pbs.twimg.com/ext_tw_video_thumb/1332744448724307969/pu/img/fZGy15pnJJIpnqXL.jpg',
          url: 'https://t.co/VReJvEzRDT',
          display_url: 'pic.twitter.com/VReJvEzRDT',
          expanded_url:
            'https://twitter.com/pollomarzo/status/1332744541166768134/video/1',
          type: 'photo',
          sizes: {
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 383, h: 680, resize: 'fit' },
            large: { w: 720, h: 1280, resize: 'fit' },
            medium: { w: 675, h: 1200, resize: 'fit' },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 1332744448724308000,
          id_str: '1332744448724307969',
          indices: [22, 45],
          additional_media_info: { monetizable: false },
          media_url:
            'http://pbs.twimg.com/ext_tw_video_thumb/1332744448724307969/pu/img/fZGy15pnJJIpnqXL.jpg',
          media_url_https:
            'https://pbs.twimg.com/ext_tw_video_thumb/1332744448724307969/pu/img/fZGy15pnJJIpnqXL.jpg',
          url: 'https://t.co/VReJvEzRDT',
          display_url: 'pic.twitter.com/VReJvEzRDT',
          expanded_url:
            'https://twitter.com/pollomarzo/status/1332744541166768134/video/1',
          type: 'video',
          video_info: {
            aspect_ratio: [9, 16],
            duration_millis: 1927,
            variants: [
              {
                bitrate: 2176000,
                content_type: 'video/mp4',
                url:
                  'https://video.twimg.com/ext_tw_video/1332744448724307969/pu/vid/720x1280/-WGWmUgvd3RTRGXQ.mp4?tag=10',
              },
              {
                content_type: 'application/x-mpegURL',
                url:
                  'https://video.twimg.com/ext_tw_video/1332744448724307969/pu/pl/DzXgn6LOIwKi4CnF.m3u8?tag=10',
              },
              {
                bitrate: 632000,
                content_type: 'video/mp4',
                url:
                  'https://video.twimg.com/ext_tw_video/1332744448724307969/pu/vid/320x568/U7UF62FDb9I0v4qs.mp4?tag=10',
              },
              {
                bitrate: 832000,
                content_type: 'video/mp4',
                url:
                  'https://video.twimg.com/ext_tw_video/1332744448724307969/pu/vid/360x640/L6VwfDt0B1B1bozd.mp4?tag=10',
              },
            ],
          },
          sizes: {
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 383, h: 680, resize: 'fit' },
            large: { w: 720, h: 1280, resize: 'fit' },
            medium: { w: 675, h: 1200, resize: 'fit' },
          },
        },
      ],
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606586034467',
  },
  {
    created_at: 'Sat Nov 28 17:54:11 +0000 2020',
    id: 1332744612247728000,
    id_str: '1332744612247728128',
    text: 'This is geolocated to a restaurant',
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 22,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '07d9d4f72e485001',
      url: 'https://api.twitter.com/1.1/geo/id/07d9d4f72e485001.json',
      place_type: 'poi',
      name: 'Taverna del Farneto',
      full_name: 'Taverna del Farneto',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.405824, 44.435644],
            [11.405824, 44.435644],
            [11.405824, 44.435644],
            [11.405824, 44.435644],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606586051414',
  },
  {
    created_at: 'Sat Nov 28 17:54:27 +0000 2020',
    id: 1332744679310434300,
    id_str: '1332744679310434307',
    text: 'This is geolocated to a city',
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 23,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606586067403',
  },
  {
    created_at: 'Sat Nov 28 17:54:45 +0000 2020',
    id: 1332744753335705600,
    id_str: '1332744753335705603',
    text: 'This is a retweet',
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 24,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    quoted_status_id: 1332744612247728000,
    quoted_status_id_str: '1332744612247728128',
    quoted_status: {
      created_at: 'Sat Nov 28 17:54:11 +0000 2020',
      id: 1332744612247728000,
      id_str: '1332744612247728128',
      text: 'This is geolocated to a restaurant',
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      truncated: false,
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 1313488616656642000,
        id_str: '1313488616656642049',
        name: 'schifo scimmia',
        screen_name: 'pollomarzo',
        location: null,
        url: null,
        description: null,
        translator_type: 'none',
        protected: false,
        verified: false,
        followers_count: 1,
        friends_count: 0,
        listed_count: 0,
        favourites_count: 0,
        statuses_count: 23,
        created_at: 'Tue Oct 06 14:38:15 +0000 2020',
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        profile_background_color: 'F5F8FA',
        profile_background_image_url: '',
        profile_background_image_url_https: '',
        profile_background_tile: false,
        profile_link_color: '1DA1F2',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        profile_image_url:
          'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
        profile_image_url_https:
          'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
      },
      geo: null,
      coordinates: null,
      place: {
        id: '07d9d4f72e485001',
        url: 'https://api.twitter.com/1.1/geo/id/07d9d4f72e485001.json',
        place_type: 'poi',
        name: 'Taverna del Farneto',
        full_name: 'Taverna del Farneto',
        country_code: 'IT',
        country: 'Italy',
        bounding_box: {
          type: 'Polygon',
          coordinates: [
            [
              [11.405824, 44.435644],
              [11.405824, 44.435644],
              [11.405824, 44.435644],
              [11.405824, 44.435644],
            ],
          ],
        },
        attributes: {},
      },
      contributors: null,
      is_quote_status: false,
      quote_count: 0,
      reply_count: 0,
      retweet_count: 0,
      favorite_count: 0,
      entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
      favorited: false,
      retweeted: false,
      filter_level: 'low',
      lang: 'en',
    },
    quoted_status_permalink: {
      url: 'https://t.co/4Jyons51PU',
      expanded: 'https://twitter.com/pollomarzo/status/1332744612247728128',
      display: 'twitter.com/pollomarzo/sta…',
    },
    is_quote_status: true,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606586085052',
  },
  {
    created_at: 'Sat Nov 28 17:55:09 +0000 2020',
    id: 1332744857694113800,
    id_str: '1332744857694113792',
    text: 'This is a comment',
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: 1332744753335705600,
    in_reply_to_status_id_str: '1332744753335705603',
    in_reply_to_user_id: 1313488616656642000,
    in_reply_to_user_id_str: '1313488616656642049',
    in_reply_to_screen_name: 'pollomarzo',
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 25,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606586109933',
  },
  {
    created_at: 'Sat Nov 28 17:55:37 +0000 2020',
    id: 1332744974983712800,
    id_str: '1332744974983712768',
    text: 'This contains a hashtag #12340987',
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 26,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606586137897',
  },
  {
    created_at: 'Sat Nov 28 17:56:16 +0000 2020',
    id: 1332745138905489400,
    id_str: '1332745138905489409',
    text: 'This mentions someone @12340987abcdefgh',
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1313488616656642000,
      id_str: '1313488616656642049',
      name: 'schifo scimmia',
      screen_name: 'pollomarzo',
      location: null,
      url: null,
      description: null,
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 1,
      friends_count: 0,
      listed_count: 0,
      favourites_count: 0,
      statuses_count: 27,
      created_at: 'Tue Oct 06 14:38:15 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
    },
    geo: null,
    coordinates: null,
    place: {
      id: '1cdc7d8b277d9aaa',
      url: 'https://api.twitter.com/1.1/geo/id/1cdc7d8b277d9aaa.json',
      place_type: 'city',
      name: 'San Lazzaro di Savena',
      full_name: 'San Lazzaro di Savena, Emilia Romagna',
      country_code: 'IT',
      country: 'Italy',
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [11.358342, 44.405735],
            [11.358342, 44.490729],
            [11.486285, 44.490729],
            [11.486285, 44.405735],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1606586176979',
  },
];
